
[deployment]
run = "NODE_ENV=production node start.js"
build = "npm install --include=dev && vite build && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist && node scripts/post-build.js"
ignorePaths = [".git", "node_modules/.cache", "*.log", "client/src"]

[nix]
channel = "stable-24_05"

[deployment.env]
NODE_ENV = "production"
