
[deployment]
run = "NODE_ENV=production node dist/index.js"
build = "vite build && esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
ignorePaths = [".git", "node_modules/.cache", "*.log", "client/src"]

[nix]
channel = "stable-24_05"

[deployment.env]
NODE_ENV = "production"
